// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_bestscore = "CgkItIz28tIOEAIQEg"; // <GPGSID>
        public const string achievement_skilled = "CgkItIz28tIOEAIQCQ"; // <GPGSID>
        public const string achievement_proficient = "CgkItIz28tIOEAIQDQ"; // <GPGSID>
        public const string achievement_advanced = "CgkItIz28tIOEAIQDw"; // <GPGSID>
        public const string achievement_experienced = "CgkItIz28tIOEAIQDg"; // <GPGSID>
        public const string achievement_beginner = "CgkItIz28tIOEAIQBw"; // <GPGSID>
        public const string achievement_expert = "CgkItIz28tIOEAIQEQ"; // <GPGSID>
        public const string achievement_skillful = "CgkItIz28tIOEAIQCw"; // <GPGSID>
        public const string achievement_talented = "CgkItIz28tIOEAIQCA"; // <GPGSID>
        public const string achievement_seasoned = "CgkItIz28tIOEAIQDA"; // <GPGSID>
        public const string achievement_novice = "CgkItIz28tIOEAIQBQ"; // <GPGSID>
        public const string achievement_senior = "CgkItIz28tIOEAIQEA"; // <GPGSID>
        public const string achievement_newbie = "CgkItIz28tIOEAIQBA"; // <GPGSID>
        public const string achievement_intermediate = "CgkItIz28tIOEAIQCg"; // <GPGSID>
        public const string achievement_rookie = "CgkItIz28tIOEAIQBg"; // <GPGSID>

}

